---
- name: provision development environment
  hosts: all
  roles:
    - base
  tasks:
    - name: set kernel release
      command: uname -r
      register: kernel_release
      changed_when: no
    - name: upgrade linux headers
      become: yes
      apt:
        name:
          - "linux-headers-{{ kernel_release.stdout }}"
    - name: set hostname
      become: yes
      hostname:
        name: anvil.local
    - name: generate SSH key
      user:
        ssh_key_bits: 4096
        ssh_key_comment: "{{ user.email }}"
    # TODO: install git hooks to PieCentral
